name: Projeto Portifolio Pessoal - API

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PORT: 3000
      API_BASE_URL: "http://localhost:3000"

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Instalar wait-on
        run: npm install -g wait-on

      - name: Iniciar servidor da API
        run: |
          npm start &
          sleep 2

      - name: Aguardar API subir
        run: wait-on http://localhost:3000/articles

      - name: Executar testes da API
        run: npm test
